{
  "id":"#FILE:content",
  "name":"content",
  "entity_type_ref":"FILE",
  "status":"unlocked",
  "properties":[
    {"id":"ASSET::#FILE:content","property_type_ref":"asset","ruleset_ref":"RULESET_ASSET","status":"unlocked","value":{"asset_ref":"Assets/FILE/%23FILE%3Acontent.json","file_type_ref":"json","properties":{}}},
    {"id":"DATA_CONTENT_COLLECTION","property_type_ref":"data","ruleset_ref":"RULESET_DATA","status":"unlocked","value":{"data_type_ref":"content_collection","value":null,"schema_ref":"SCHEMA_CONTENT_COLLECTION","properties":{}}}
  ]
}
