{
  "id":"#FILE:index",
  "name":"index",
  "entity_type_ref":"FILE",
  "status":"unlocked",
  "properties":[
    {"id":"ASSET::#FILE:index","property_type_ref":"asset","ruleset_ref":"RULESET_ASSET","status":"unlocked","value":{"asset_ref":"Assets/FILE/%23FILE%3Aindex.html","file_type_ref":"html","properties":{}}},
    {"id":"SCHEMA_PAGE_REQUEST","property_type_ref":"schema","ruleset_ref":"RULESET_SCHEMA","status":"unlocked","value":{"schema_type_ref":"record","definition":{"fields":{"page_id":{"type":"string","required":true}}},"properties":{}}},
    {"id":"SCHEMA_RENDERED_DOCUMENT","property_type_ref":"schema","ruleset_ref":"RULESET_SCHEMA","status":"unlocked","value":{"schema_type_ref":"record","definition":{"fields":{"html":{"type":"string","required":true},"status":{"type":"string","required":true}}},"properties":{}}},
    {"id":"DATA_PAGE_REQUEST","property_type_ref":"data","ruleset_ref":"RULESET_DATA","status":"unlocked","value":{"data_type_ref":"page_request","value":{"page_id":"home"},"schema_ref":"SCHEMA_PAGE_REQUEST","properties":{}}},
    {"id":"DATA_INDEX_DOCUMENT","property_type_ref":"data","ruleset_ref":"RULESET_DATA","status":"unlocked","value":{"data_type_ref":"rendered_document","value":null,"schema_ref":"SCHEMA_RENDERED_DOCUMENT","properties":{}}},
    {"id":"EVENT_OPEN_PAGE","property_type_ref":"event","ruleset_ref":"RULESET_EVENT","status":"unlocked","value":{"event_type_ref":"open_page","properties":{}}},
    {"id":"FUNCTION_OPEN_PAGE","property_type_ref":"function","ruleset_ref":"RULESET_FUNCTION","status":"unlocked","value":{"function_type_ref":"open_page","input_refs":["DATA_PAGE_REQUEST"],"output_refs":[],"logic":{"primitive_set_ref":"CW_LOGIC_PRIMITIVES","body":[{"op":"emit","cause_ref":"LINK_OPEN_PAGE_CAUSES_RENDER_PAGE"},{"op":"return"}]},"properties":{}}},
    {"id":"LINK_PAGE_REQUEST_INPUT","property_type_ref":"link","ruleset_ref":"RULESET_LINK_EVENT_INPUT","status":"unlocked","value":{"link_type_ref":"event_input","parent_ref":"DATA_PAGE_REQUEST","child_ref":"EVENT_OPEN_PAGE","properties":{}}},
    {"id":"LINK_OPEN_PAGE_HANDLER","property_type_ref":"link","ruleset_ref":"RULESET_LINK_EVENT_HANDLER","status":"unlocked","value":{"link_type_ref":"event_handler","parent_ref":"EVENT_OPEN_PAGE","child_ref":"FUNCTION_OPEN_PAGE","properties":{}}},
    {"id":"REQ_INDEX_RENDERER","property_type_ref":"required_link","ruleset_ref":"RULESET_REQUIRED_LINK","status":"unlocked","value":{"link_type_ref":"dependency","self_endpoint":"child_ref","min":1,"max":1,"other_endpoint":{"entity_type_ref":"FILE"},"properties":{}}},
    {"id":"LINK_INDEX_RENDERER_DEPENDENCY","property_type_ref":"link","ruleset_ref":"RULESET_LINK_DEPENDENCY","status":"unlocked","value":{"link_type_ref":"dependency","parent_ref":"#FILE:renderer","child_ref":"#FILE:index","required_link_ref":"REQ_INDEX_RENDERER","properties":{}}}
  ]
}
