{
  "id":"#ABS:UltralightCMS",
  "name":"Ultralight CMS",
  "entity_type_ref":"ABS",
  "status":"unlocked",
  "properties":[
    {
      "id":"MEMBERS::#ABS:UltralightCMS",
      "property_type_ref":"members",
      "ruleset_ref":"RULESET_MEMBERS",
      "status":"unlocked",
      "value":{
        "member_refs":[
          "#ABS:UltralightCMS:RenderPipeline",
          "#CTRCT:UltralightCMS",
          "#FILE:index",
          "#FILE:renderer",
          "#FILE:content",
          "#FILE:style",
          "#DOC:UltralightCMS:Architecture",
          "#DOC:UltralightCMS:Runtime",
          "#DOC:UltralightCMS:Package",
          "#DOC:UltralightCMS:Flow"
        ],
        "properties":{}
      }
    }
  ]
}
